(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.help = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// t1
	this.t1 = new lib.t1();
	this.t1.setTransform(304.7,301,1.5,1.5,0,0,0,187.2,17.5);

	this.timeline.addTween(cjs.Tween.get(this.t1).wait(62).to({x:304.6,y:31,alpha:0},59,cjs.Ease.get(-0.99)).to({_off:true},1).wait(585));

	// p3
	this.instance = new lib.p3();
	this.instance.setTransform(512.2,668.9,1.5,1.5,0,0,0,62.8,62.8);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(118).to({_off:false},0).to({y:245.9,alpha:0.941},31,cjs.Ease.get(1)).to({y:299.9,alpha:1},23).wait(27).to({scaleX:0.75,scaleY:0.75,x:407.2,y:464.8},35).to({y:356.8,alpha:0},21).to({_off:true},1).wait(451));

	// p2
	this.instance_1 = new lib.p2();
	this.instance_1.setTransform(303,667.4,1.5,1.5,0,0,0,62.8,62.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(92).to({_off:false},0).to({y:245.9,alpha:0.941},31,cjs.Ease.get(1)).to({y:298.4,alpha:1},23).wait(53).to({scaleX:0.75,scaleY:0.75,x:302.9,y:463.3},35).to({y:355.3,alpha:0},21).to({_off:true},1).wait(451));

	// p1
	this.instance_2 = new lib.p1();
	this.instance_2.setTransform(93.7,667.4,1.5,1.5,0,0,0,62.8,62.8);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(105).to({_off:false},0).to({y:245.9,alpha:0.941},31,cjs.Ease.get(1)).to({y:298.4,alpha:1},23).wait(40).to({scaleX:0.75,scaleY:0.75,x:198.7,y:463.3},35).to({y:355.3,alpha:0},21).to({_off:true},1).wait(451));

	// w1
	this.instance_3 = new lib.wait();
	this.instance_3.setTransform(265,313.7,1.5,1.5,0,0,0,6.5,6.5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(286).to({_off:false},0).to({_off:true},72).wait(349));

	// w2
	this.instance_4 = new lib.wait();
	this.instance_4.setTransform(310,313.7,1.5,1.5,0,0,0,6.5,6.5);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(312).to({_off:false},0).to({_off:true},46).wait(349));

	// w3
	this.instance_5 = new lib.wait();
	this.instance_5.setTransform(355,313.7,1.5,1.5,0,0,0,6.5,6.5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(336).to({_off:false},0).to({_off:true},22).wait(349));

	// $B
	this.B = new lib.bowser();
	this.B.setTransform(307,643.7,1.5,1.5);
	this.B.alpha = 0;
	this.B._off = true;

	this.timeline.addTween(cjs.Tween.get(this.B).wait(204).to({_off:false},0).to({y:276.2,alpha:1},82,cjs.Ease.get(1)).wait(72).to({scaleX:0.75,scaleY:0.75,alpha:0},26,cjs.Ease.get(-0.99)).to({_off:true},1).wait(322));

	// like
	this.instance_6 = new lib.like();
	this.instance_6.setTransform(433.8,228.1,1.5,1.5,0,0,0,53.7,45.8);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(629).to({_off:false},0).to({scaleX:1.55,scaleY:1.55,x:493.3,alpha:1},30,cjs.Ease.get(-0.99)).to({scaleX:1.5,scaleY:1.5,x:478.8},9,cjs.Ease.get(-0.99)).wait(39));

	// arrow
	this.instance_7 = new lib.arrow();
	this.instance_7.setTransform(370.7,241.8,1.5,1.5,0,0,0,16.9,10.5);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(599).to({_off:false},0).to({alpha:1},30,cjs.Ease.get(-0.99)).wait(78));

	// fb
	this.instance_8 = new lib.fb();
	this.instance_8.setTransform(284.2,241.7,1.5,1.5,0,0,0,37.6,37.6);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(569).to({_off:false},0).to({alpha:1},30,cjs.Ease.get(-0.99)).wait(108));

	// arrow
	this.instance_9 = new lib.arrow();
	this.instance_9.setTransform(199.1,241.8,1.5,1.5,0,0,0,16.9,10.5);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(539).to({_off:false},0).to({alpha:1},30,cjs.Ease.get(-0.99)).wait(138));

	// GIF
	this.instance_10 = new lib.GIF();
	this.instance_10.setTransform(303,294.6,0.75,0.75,0,0,0,62.8,62.8);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(358).to({_off:false},0).to({scaleX:2.4,scaleY:2.4,x:296.9,y:242.1,alpha:1},40,cjs.Ease.get(-0.99)).to({scaleX:2.25,scaleY:2.25,x:297,y:249.6},18,cjs.Ease.get(1)).to({y:249.7},79).to({regX:63,regY:63,scaleX:0.75,scaleY:0.75,rotation:-359.9,x:121.5,y:242.1},44,cjs.Ease.get(-0.99)).wait(168));

	// t2
	this.instance_11 = new lib.t2();
	this.instance_11.setTransform(307,367.6,0.75,0.75,0,0,0,156.8,19.4);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(358).to({_off:false},0).to({scaleX:1.59,scaleY:1.59,y:441.1,alpha:1},40,cjs.Ease.get(-0.99)).to({regY:19.5,scaleX:1.5,scaleY:1.5,y:436.7},18,cjs.Ease.get(1)).wait(79).to({alpha:0},29,cjs.Ease.get(-0.99)).to({_off:true},1).wait(182));

	// t3
	this.instance_12 = new lib.t3();
	this.instance_12.setTransform(307,378.9,1.5,1.5,0,0,0,89.6,19.5);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(524).to({_off:false},0).to({alpha:1},29,cjs.Ease.get(1)).wait(51).to({alpha:0},30,cjs.Ease.get(-0.99)).to({_off:true},1).wait(72));

	// t4
	this.instance_13 = new lib.t4();
	this.instance_13.setTransform(307,379.7,1.5,1.5,0,0,0,124.6,19.5);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(634).to({_off:false},0).to({alpha:1},30,cjs.Ease.get(-0.99)).wait(43));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(23.9,274.8,561.5,52.6);


// symbols:
(lib.wait = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgtAtQgSgSgBgbQABgZASgUQAUgSAZgBQAbABASASQAUAUgBAZQABAbgUASQgSAUgbgBQgZABgUgUg");
	this.shape.setTransform(6.5,6.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,13,13);


(lib.t4 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("APmCbQgMgFAAgNQAAgOAMgCIAIAAQALADAKAAQAGAAAAgGIAAglIg4AAQAFADABAGQAAAFgEAGQgHAKgNALQgMAMgQAMQgJAIgKAAQgHAAgFgFQgFgEgBgIQABgFAGgFQAZgSAZgYIAIgEIgRAAQgKAAgEgGQgFgEAAgKIAAggQAAgJAFgEQAEgGAKAAIDcAAQAKAAAFAGQAFAEAAAJIAAAgQAAAUgUAAIgjAAIADABQA3AjAOAOQAEAEAAAFQAAAHgEAFQgFAGgIAAQgHAAgFgEIhGg2QgDgDAAgGQAAgFAFgEIACgBIglAAIAAAvQAAAPgIAIQgFAEgHACQgHACgKABQgagBgKgEgAO9AqIAAAGQAAAHAGAAICzAAQAFAAAAgHIAAgGQAAgFgFAAIizAAQgGAAAAAFgAFACbQgEgDAAgJIAAgOQhMAMgjABQgIgBgDgDQgDgFgBgHQAAgIADgDQAFgEAKgBIALAAIAAhuIgOAAQgHAAgEgDQgEgDAAgJQAAgIAEgEQAEgDAHAAIEkAAQAIAAADADQAEADAAAJQAAAHgDADQgEAFgIAAIiUAAIAACPQAAAJgEADQgEAEgIABQgJgBgEgEgAD8BrIBAgGIAAgOIhAAAgAD8A7IBAAAIAAgPIhAAAgAD8AQIBAAAIAAgQIhAAAgAHECOIgVgNQgRAOgSALQgHADgKABQgJAAgEgGQgDgEAAgGQAAgHAFgGIAigVIgYgVQgGgFgEgHQgDgGAAgFQAAgFAEgEQAEgDAFAAQAEAAAHADQASASAUAPIAMgKQATgSADgNQAAgBgBAAQAAgBAAAAQgBAAgBAAQAAAAgBAAIhVAAQgHAAgDgFQgEgDAAgIQAAgHAEgDQADgEAHgBIBmAAQAMABAGAEQAHAFAAAKQAAAIgEALQgEAKgIANQgMAQgOAPQAYANAZAJQAIAEAAAJQAAAIgFAFQgEADgIAAQgQAAgdgQgAIiCYQgFgFAAgHIAFgUQAIgcAFgbQAEgbACgaIABh4QAAgNAHgHQAHgGAOAAIBqAAIAAgIQAAgHAGgGQADgDAKgBQALABAEADQAGAFAAAIIAAAIIBrAAQAHAAADAEQADAEAAAHQAAAIgDAEQgDADgHAAIjwAAQgHAAAAAGIAABSQASgVANgUQAOgUAJgTQAEgEAFAAQAHAAAFAEQAGAEAAAGQAAAEgDAEQgHARgLARIAABgQAAANgQAAQgHAAgEgDQgEgEAAgGIAAg2IgFAEQgIAEgGABQgGgBgFgFQgEBTgSA4IgEAJQgEAGgKAAQgIAAgFgDgAKxCaQgNgBgFgHQgFgGAAgOIAAgtQAAgQARAAQAQAAAAAQIAAAlQAAAIAHAAIA4AAQAGgBABgGQACgFAAgMQACgLAOAAQAHAAAEADQAGAFAAAHQAAARgGAPQgDAIgIADQgHAFgLAAgANECVIgEgEIgeg7QgCgDAAgEIACgGQACgEAEgDIAJgBQAFABAGAFQAIAIAOAeQAJASAAAMQAAAFgDADQgFAEgHAAQgGAAgCgCgAJYCTQgGgDAAgIIADgJQAMgXAJgbIAEgEIAGgCQAHAAAGACQAGAEAAAHQAAAGgDAJQgMAfgHAMQgGAJgHAAQgHAAgFgEgAh+CXQgWAAAAgWIAAg7QAAgXAWAAIBLAAQAWAAAAAXIAAA7QAAAWgWAAgAhyBVIAAAcQAAAFAFAAIAoAAQAFAAAAgFIAAgcQAAgEgFAAIgoAAQgFAAAAAEgAn4CPQgEgFAAgJQAAgHAIgGIAdgLIAAjyQAAgJAEgEQAEgFAKAAQALAAAEAFQAEAEAAAJIAABBIBCAAQAKAAAEADQAFAEAAAMQAAAIgDAEQgFAHgLAAIhCAAIAAB+IA6gTIAPgCQAEgBAEAEQAFAEAAAHQAAAKgFAHQg0AZhDAUQgHACgOAAQgHABgEgHgAy0CPQgEgFAAgJQAAgHAIgGIAdgLIAAjyQAAgJAEgEQAEgFAKAAQALAAAEAFQAEAEAAAJIAABBIBCAAQAKAAAEADQAFAEAAAMQAAAIgDAEQgFAHgLAAIhCAAIAAB+IA6gTIAPgCQAEgBAEAEQAFAEAAAHQAAAKgFAHQg0AZhDAUQgHACgOAAQgHABgEgHgAANCUQgXAAAAgYIAAh8QgEACgGAAQgIAAgFgCQgFgEAAgHQABgFADgGQAdg7ANhDQAEgIAHgCQAJAAAGADQAGAEAAAJIgIAmIAnAAQAFgRACgUQACgHADgDQAEgEAGAAQAIABAGAEQAHADAAAJIgBAFIgHAdIAjAAQAJAAADADQAFAEAAAKQAAAHgDADQgEAGgKAAIgmAAIAAApIAfAAQAKAAADAEQAEACAAAKQAAAIgDADQgEAEgKAAIgfAAIAAApIAfAAQAKAAADAEQAEADAAAJQAAAIgDAEQgEAEgKAAIgfAAIAAAqIAqAAQARAAAAAQQAAAQgRAAgAAWBuQAAAGAEAAIApAAIAAgqIgtAAgAAWAqIAtAAIAAgpIgtAAgAAWgeIAtAAIAAgpIgtAAgAkwCTQgJgBgHgCQgHgDgEgFQgEgFgBgHIgCgSIAAj3QAAgRASAAQATAAAAARIAABUQAZgGA0gUQAJgEAGAAQAHAAAGAEQAHAGAAAIQgBAJgGAIQgJAGgPAFIhRAXIAAB5QAAAHAHAAIA0AAQAIgBABgOQADgNAAgbQACgNAOAAQAKABAFADQAHAFAAAIQAAAggIAbQgGAbgbACgAvsCTQgJgBgHgCQgHgDgEgFQgEgFgBgHIgCgSIAAj3QAAgRASAAQATAAAAARIAABUQAZgGA0gUQAJgEAGAAQAHAAAGAEQAHAGAAAIQgBAJgGAIQgJAGgPAFIhRAXIAAB5QAAAHAHAAIA0AAQAIgBABgOQADgNAAgbQACgNAOAAQAKABAFADQAHAFAAAIQAAAggIAbQgGAbgbACgALpBpIgcgRIgCgDQgDgDgBgFQAAgGAEgEQAEgFAGAAIAGACQAQAJAMAJQAEAFAAAEQAAAFgDAEQgDAEgGACgALJA5QgZAAAAgZIAAgcIgIADQgIgBgEgFQgFgBAAgGIADgHQANgSAJgTQAKgTAGgTQADgKAHAAQAIAAAFACQAGAEAAAIIgBAGIAmAAIAEgMQAEgIANAAQAHAAAEACQAEADABAGIgDAJIAiAAQAHAAADACQADADAAAHQAAAGgCACQgDAFgIAAIgqAAIAAANIAkAAQAFAAACACQAEADAAAGQAAAGgCACQgDAFgGAAIgkAAIAAANIAkAAQAFAAACADQAEAAAAAHQAAAFgCACQgDAFgGAAIgkAAIAAANIAzAAQAMAAAAANQAAAMgMAAgALPAcQAAAEAEAAIAoAAIAAgNIgsAAgALPgDIAsAAIAAgNIgsAAgALPgsIAAAEIAsAAIAAgNIgoAAgAiBAdQgIAAgDgDQgEgDAAgJQAAgHAEgFQADgCAIAAIBOAAQAIAAAEACQADAEAAAIQAAAIgDADQgEAEgIAAgAtBAQQgKAAgGgFQgFgEAAgKQAAgKAFgFQAGgGAKABIERAAQALgBAFAGQAFADAAAMQAAAIgEAFQgFAFgMABgAOMAAQgGAAgEgDQgEgDAAgJQAAgJAEgCQADgDAHAAIB6AAIAAgIQAAgEACgEIhWAAQgLAAgFgGQgGgFAAgLIAAg9QAAgKAGgFQAFgGALAAIDUAAQAWAAAAAVIAAA9QAAALgFAFQgGAGgLAAIhWAAIABAIIAAAIIB6AAQAHABAEADQADACAAAIQAAAIgCACQgEAFgIAAgAPAhOQAAAGAFAAICuAAQAFAAAAgGIAAgHIi4AAgAPAh0IAAAGIC4AAIAAgGQAAgFgFgBIiuAAQgFABAAAFgAiBgQQgIAAgDgEQgEgDAAgIQAAgIAEgEQADgEAIAAIBOAAQAIAAAEAEQADADAAAJQAAAHgDADQgEAFgIAAgAD6grQgYAAAAgaIAAg9QAAgZAYAAIDMAAQAZAAAAAZIAAA9QAAAagZAAgAEGhOQAAAHAGAAICpAAQAGAAAAgHIAAgIIi1AAgAEGh4IAAAGIC1AAIAAgGQAAgIgGAAIipAAQgGAAAAAIgAiOg+QgIAAgEgFQgEgEAAgKQAAgIAEgFQAEgDAIAAIBrAAQAJAAAEAEQAEADAAAJQAAAJgDADQgFAGgJABgAh/hyQgHAAgEgDQgFgEAAgJQAAgKAFgDQADgDAIAAIBMAAQAIAAADADQAEACAAALQAAAIgCADQgEAGgJgBg");
	this.shape.setTransform(124.4,19.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.5,3.6,241.9,32);


(lib.t3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmcCXQgNgFAAgNQABgGAEgFQADgEAHAAIALACQAUAGAUAAQALAAAAgUIgCgNIiPAAQgHAAgEgEQgEgDAAgKQAAgHAEgEQAEgEAHAAICDAAQAAgGAGgFQAHgEAIABQALgBAGALIABABQATgGAMgFQAJgFACgCQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAgBAAIjGAAQgJAAgCgEQgEgEAAgHQAAgHAEgFQADgEAIAAIDkAAQATABAEAGQAIAGAAAKQgBAHgGAHQgKAKgPAIIAuAAQAIAAAFAEQACADAAAIQABAJgDACQgEAGgJAAIhnAAIACASQAAAZgMAMQgOAMgXAAQghAAgUgJgAGWCcQgIgDgBgLQABgEAEgFQAPgSAJgTQAKgUADgPIgLAAQgKAAgFgEQgFgGgBgKIAAgyQAAgUAVAAIAvAAQAUAAAAAUIAAAyQAAAKgFAGQgFAEgKAAIgFAAIAAADQAAAIgEAMIgDAHQAKAOAaAZQAFADABAIQAAAGgDAEQgFAHgIgBQgNABgYgmQgKAWgJAJQgHAIgKAAQgGAAgEgDgAG3ADIAAAZQAAAEAFAAIAOAAQAGAAgBgEIAAgZQABgDgGgBIgOAAQgFABAAADgAE0CbQgHgDAAgKQAAgEADgFQANgSAHgRQAJgTACgPIAAgDIgGAAQgTABAAgUIAAg1QAAgJAFgEQAFgFAJAAIAsAAQAKAAAFAFQAFAEgBAJIAAA1QABAUgUgBIgIAAIACAGIgDAMIAEACQAHAGAMARQAMAQAAAJQAAAGgEAEQgFAFgJAAQgGAAgEgGIgRgaIgLAYQgEAKgFAFQgGAHgJgBQgGAAgFgCgAFWACIAAAbQAAAEAEgBIALAAQAEABAAgEIAAgbQAAgDgEAAIgLAAQgEAAAAADgAtSCXQgFgEAAgIQAAgGAFgFQA4giAQgbQAQgXAEgsIgkAAQgNAAAAgPQgKAOgIAFQgHAFgHAAQgHgBgGgGQgGgEAAgJQAAgFAGgEQAWgaAOgWQAMgUAJgWQAEgHAKAAQAFABAFADQAIAEAAALIgCAIQgEAQgMATIgOAWICxAAQAJAAAIACQgagrgNgdQgEgIgKgBIhfAAQgQgBAAgQQABgQAPgBIBrAAQAMAAAKAHQAIAFAGAMQAgBCAZAdQAHAGAAAKQAAAJgEACQgHAHgMgBQgJgBgLgMIgDgEIgBBfQgDAsgQAOQgLALgWACQgUgBgOgCQgPgDgIgFQgIgGAAgOQABgGAEgFQAFgFAGAAIAKADQARAFAPABQASgBADgWQABgxAAgqQAAgBAAgBQAAgBAAAAQAAAAAAAAQAAAAgBAAIhcAAQgEApgMAdQgMAYgSATQgTAUgbAQQgNAIgMAAQgHABgHgHgAD2CbQgGgCgEgGQgDgFABgIQABgGAEgEQAEgEAFAAIADAAIAIABQAGAAAAgGIAAg6IgfAAQgDAwgGAiIgGAKQgCAFgKABQgIgBgFgDQgEgEAAgGIACgPQAHgfAEg3IAAidQAAgNAHgHQAHgGANAAIAqAAQANAAAHAHQAGAHAAAOIAADsQAAAMgBAGQgCAIgEACQgGAHgUAAgADrAZIAeAAIAAgvIgeAAgADrhnIAAAwIAeAAIAAgrQAAgMgIAAIgPAAQgHAAAAAHgAJICZQgNAAgFgGQgHgGABgMIAAg4QgBgNAHgGQAFgGANAAIDiAAQALAAAHAGQAGAGAAANIAAA4QAAAYgYAAgAJVB4QABAGAFAAIC7AAQAGAAAAgGIAAgIIjHAAgAJVBRIAAAGIDHAAIAAgGQAAgFgGgBIi7AAQgFABgBAFgAiPCTQgIAAgGgFQgEgDAAgKQAAgJAEgGQAGgDAIAAIB7AAIAAgpIhqAAQgIAAgFgEQgEgEAAgKQAAgIAEgFQAFgDAIAAIBqAAIAAgWQABgIAEgEQAEgDALAAQAHAAAEADQAGADAAAJIAAAWIBrAAQAIAAAFADQACADAAAKQAAAIgCAEQgFAGgIAAIhrAAIAAApIB6AAQALAAAEAEQADADAAALQABAHgEAFQgEAFgLABgAInAlQgGAAgDgEQgDgCAAgIQAAgGADgDQADgDAGAAIB/AAIAAgLIh0AAQgHAAgDgBQgCgCAAgIQAAgFACgEQADgDAHABIB0AAIAAgQIhqAAQgKAAgBgMQABgMAKAAIBqAAIAAgPIh+AAQgGAAgDgEQgDgCAAgIQAAgGADgEQADgCAGAAIB+AAIAAgPIhqAAQgKgBgBgLQABgNAKAAIBqAAQABgHAEgFQAEgEAKAAQALAAAEAEQAEAEAAAIIBeAAQAKAAAFAFQAFAEAAAIIAAAXIARAAQAGAAADACQADADAAAHQAAAHgCACQgEAFgGAAIgRAAIAAAUQAAATgUAAIheAAIAAAQIByAAQAHgBACADQADADAAAGQAAAGgCADQgDACgHAAIhyAAIAAALICBAAQAHAAADADQACADAAAGQABAHgDACQgDAFgHAAgALMg+IBJAAQABAAAAAAQABAAAAgBQAAAAAAgBQABAAAAgBIAAgMIhMAAgALMhnIBMAAIAAgLQAAgEgFAAIhHAAgABxgHIgQgVQgnAJgsAFQhEAHhNABQgKAAgDgEQgGgEAAgKQABgHACgFQAEgGAMABIAegBIAhg+IhHAAQgIgBgFgEQgFgDAAgKQAAgKAFgEQAFgFAIABIEUAAQAJgBAFAFQADADAAALQAAAHgCAFQgGAFgJABIijAAIghA9QAwgCBRgJIgXgVQgEgGAAgFQgBgGAHgFQAFgDAIgBQAGABAIAFQARALAQAPQAQAPAOASQAGAKABAHQAAALgEAFQgFADgKAAQgJAAgFgHgAnJgJQgLAAgGgFQgGgGAAgLIAAghQAAgKAGgGQAGgFALAAIDTAAQAXAAAAAVIAAAhQAAAWgXAAgAm4gzIAAAIQAAAFAEAAICpAAQAGAAAAgFIAAgIQAAgGgGAAIipAAQgEAAAAAGgAEwgvQgEgGgBgHQABgHAGgFQApgmAhgmQALgLALAAQALAAALALQApAsAlAdQAGAFgBAGQABALgIAGQgFAGgKAAQgEAAgFgGIgSgQIAAADQAAAGgDADQgEAGgIgBIhSAAQgHAAgEgDQgEgDAAgHIgNAOQgHAGgGAAQgKAAgGgIgAG+hMIgngqQgDgDgCAAIgEACIglArIBVAAgAnthmQgHAAgEgDQgEgEAAgJQAAgIAEgEQAEgDAHAAIB4AAIAAgHQAAgIAHgHQADgEANAAQAKAAAFAEQAGAGAAAJIAAAHIB6AAQAIAAAEADQADADAAAJQAAAHgDAEQgDAFgJAAg");
	this.shape.setTransform(89.8,19.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.9,3.4,171.9,32.1);


(lib.t2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ap2CjQgHgBgEgIQgEgHAAgPIAAhcIg5AAQgBAPgDAMQgDANgFAKQgRAjgqAXQgLAHgKAAQgIAAgHgHQgFgFgBgJQAAgIAGgGQAWgKANgKQAOgKAGgJQAMgOADgbIhAAAQgJAAgFgEQgEgEAAgKQAAgJAEgFQAFgEAJAAIEUAAQAKAAAEAEQAEADAAALQAAAIgDAEQgFAGgKAAIhQAAIAABSQAAAFAFAAIAhAAQAKgBACgLQACgIABgXQABgGAEgEIAKgDIAMACQAKACAAAMQAAARgCANQgBAOgDAJQgEAKgIAGQgHAFgLACgATgCcQgLgBgFgGQgEgEAAgHQAAgJADgEQAEgFAJgBIARAAQAGAAAAgEIAAg5QgPAEgKABQgVgBAAgSQAAgPAMgDIAigJIAAhJIgeAAQgIAAgFgEQgFgEAAgKQAAgLAFgEQAEgDAJAAIAeAAIAAg2QAAgHAFgEQAEgDAJgBQASAAABAPIAAA2IATAAQAJAAAFADQAEADAAAMQAAAJgDAEQgEAFgLAAIgTAAIAAA7IALgDQAFgDAFAAQAJAAAFADQAFAGAAAJQAAAHgHAGQgNAIgUAJIAABRQAAAOgHAHQgIAHgNACgAG5CZQgHgDgBgKQAAgEAFgGQAPgSAJgSQAKgVADgOIgLAAQgKAAgFgFQgGgFAAgLIAAgyQAAgUAVAAIAuAAQAVAAAAAUIAAAyQAAALgFAFQgFAFgLAAIgEAAIAAACQAAAIgEANIgDAGQAKAOAaAZQAFADAAAIQAAAGgDAFQgEAGgIAAQgNAAgZgmQgKAWgJAKQgGAHgKAAQgGAAgFgDgAHbAAIAAAZQAAAFAFAAIAOAAQAFAAAAgFIAAgZQAAgDgFAAIgOAAQgFAAAAADgA03CYQgFgEAAgHIAAkDQAAgMAFgGQAEgGAKAAIBSAAQALAAAFAGQAGAFAAAMIAADMQAAAPgFAFQgCAEgGACQgFADgIAAQgSAAgGgCIgJgCQgFgCgCgFQgDgDAAgFIABgHQAAgEAFgDQADgDAHAAIAQAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAgBAAgBIAAi4Ig0AAIAAD6QAAAHgFAEQgEAEgIAAQgJAAgEgEgAQRCbQgnAAgagGQgagFgMgKQgFgDgEAAIgDACQgKAJgMAIQgGAFgEAAQgHAAgCgDQgHgFgFgJIgBgHQABgHAHgFQANgGAOgLQADgDABgDIAAhGQAAgBAAAAQgBgBAAAAQAAAAgBgBQgBAAAAAAIgYAAQgJAAgDgFQgEgDAAgJQAAgHAEgDQAEgFAIAAIAmAAQALAAAGAFQAGAEAAAKIAABWQACALAOAEQALAEASACQASACAZAAICRgCQAIAAAEAEQAFAFAAAIQAAALgFAFQgDAEgLABgAFYCYQgHgDAAgJQAAgEADgGQAMgSAIgRQAJgTACgPIAAgCIgGAAQgTAAAAgTIAAg1QAAgKAFgEQAFgFAJAAIAsAAQAKAAAFAFQAEAEAAAKIAAA1QAAATgTAAIgIAAIABAFIgCAMIADACQAIAHAMAQQAMARAAAIQAAAGgFAFQgEAEgJAAQgHAAgEgGIgQgaIgLAYQgEAKgFAGQgGAGgJAAQgGgBgFgCgAF6AAIAAAaQAAAEAEAAIALAAQAEAAAAgEIAAgaQAAgDgEAAIgLAAQgEAAAAADgAhyCUQgEgFgCgIQAAgHAGgFQAwgZAOgWQAHgJAEgNQAFgOACgSIgbAAQgeAAAAgcIAAhbQAAgPAIgHQAHgIAPAAIA/AAIAIgYQAEgLAPAAQAJAAAFADQAGADABAIIgHAVIBdAAQAPAAAHAIQAIAHAAAPIAABbQAAANgIAIQgHAHgPAAIgNAAQAEAEAAAFIgCAJQgGARgMARIApgEIgIgOQgEgHAAgEQAAgGAFgEQAFgCAFAAIAIABQAGAGAJAMQATAcAAANQAAAHgEAEIgDACIACAIQAAAQgGAJQgHAKgTABIhsAAQgXgCAAglIAAhZIgZAAQgBASgEAPQgDAPgFAMQgTAnguAbQgLAHgKAAQgIAAgHgHgAA7BpIAAADQABAJAIAAIBJAAQAJAAACgCQACgBABgEQAAgGAFgDIACgBIgCgGQhFAKggABgAA7BOIAMgBIAOgZIALgaIAEgEIgpAAgAA0gHIBGAAQAHAAAAgHIAAgWIhNAAgAg2gOQAAAHAHAAIA+AAIAAgdIhFAAgAA0hCIBNAAIAAgWQAAgHgHAAIhGAAgAg2hYIAAAWIBFAAIAAgdIg+AAQgHAAAAAHgAjfCWQgJgFgHgIQgJgKgJgQQgPASgSASQgJAHgIABQgJAAgGgGQgFgFAAgJQAAgEAEgFIAMgMQAVgRARgXQgOgrgFgtQgEgYgCgcIhnAAQgIAAAAAHIAAAnIBCAAQARAAADAFQAHAFAAAOQgBA9gDAZQgDAVgIAHQgGAIgNAAIgigBQgMAAgFgGQgEgFAAgHQAAgHAEgFQAEgGAIAAIAhAAQAEgDAAhHQAAgEgEAAIg2AAQgEBLgSAxIgFAMQgFAGgLAAQgJAAgFgEQgFgEAAgIIAEgQQATgvADgpIABhqQAAgPAIgHQAHgHAPAAIB0AAIgBgmQAAgKAEgEQAEgEAKAAQAJAAAEADQAGAFAAAKIABAmIBUAAQAIAAAEAEQAEAFAAAJQAAASgQAAIhUAAIAAACQACAbAEAYQADAXAGAXIABAEQAcgsAEgZQADgMAKAAQALAAADACQAJAEAAANQAAAFgFAOQgJAUgNAWQgMAWgPAVQAFAMAGAJQAJALAGAAQAFAAAEgGIAIgQQADgHAGAAQAHAAAGADQAJAGAAALQgBAOgHAMQgLAQgNAIQgHADgJAAQgJgBgIgEgAvICXQgQgDgQgGQgJgEgBgLQAAgJAFgGQAFgFAFAAIAMABQAgAIAKAAQAFAAAAgFIAAjSIjcAAQgIAAgFgEQgFgEAAgKQAAgJAFgFQAFgEAIAAIEbAAQAKAAAEAEQAEAEAAAKQAAAIgDAEQgFAGgKAAIgYAAIAADbQAAAKgCAGQgCAHgFADQgLAIgRABQgOAAgUgEgAEaCYQgGgCgEgGQgDgFAAgIQABgGAFgEQAEgEAFAAIADABIAHABQAHAAAAgHIAAg5IggAAQgCAvgHAjIgFAJQgDAGgKAAQgHAAgFgEQgEgDAAgHIACgPQAGgfAFg2IAAidQAAgOAHgGQAHgHANAAIAqAAQANAAAHAHQAGAHAAAOIAADtQAAALgCAHQgCAHgDADQgGAGgUAAgAEOAWIAfAAIAAgvIgeAAgAEPhqIAAAwIAeAAIAAgrQAAgMgIAAIgPAAQgHAAAAAHgA1sCOIgLgZQg2AUgyABQgJAAgFgEQgFgFAAgKQAAgGADgFQAFgGAIAAIAGAAIAAjdQAAgMAGgGQAGgGAMAAIBWAAQALAAAFAGQAFAGAAAMIAACBQAAALgFAGQgFAGgLAAIhLAAIAABCQAcgEAYgIIgJgSQgFgKgBgHQAAgGAGgEQAEgCAFAAIAIABQAJAIAMAUQANAWAGARQAGAQABAKQAAAHgEAEQgEAEgKAAQgHAAgFgHgA25AAIA5AAQADAAAAgFIAAghIg8AAgA25hoIAAAhIA8AAIAAghQAAgFgDAAIg1AAQgEAAAAAFgAViCOQgbAAAAgbIAAi/QAAgbAbAAIATAAQAHgUADgVQAEgPANAAQAJAAAGAEQAIAEAAALIgKAlIA7AAQAbAAAAAbIAAC/QAAAbgbAAgAVsBjQAAAIAIAAIBSAAQAIAAAAgIIAAhBIhiAAgAVsg7IAAA6IBiAAIAAg6QAAgJgIAAIhSAAQgIAAAAAJgAKjCGQgNgFgKgJQgLgJgGgMIAAgsQAFgFAJAAQAPAAACANQAEAUAJAJQAKAKAPAAQASAAAIgLQAJgLAAgXQAAgUgOgKQgGgFgJgDQgIgCgKAAQgJAAgEgFQgEgEAAgIQAAgRAOAAQAMAAAIgCQAIgDAFgFQAGgFACgIQADgIAAgMQAAgTgIgKQgHgKgOAAQgOAAgIAHQgHAHgBAOQgBAMgFAEQgEAFgLAAQgJAAgFgGIgEgGIAAgZIAEgLQAFgLAKgIQATgRAcAAQAgAAAVASQAKAJAGAMQAFANAAAQQAAAkgiAeQASAIALAOQAMAPAAAQQAABVhPAAQgPAAgNgEgAQjBsQgDgFAAgGIAAgQIhXAAQgHAAgEgEQgEgEAAgJQAAgHAEgEQAEgEAHAAIBXAAIAAgQIgyAAQgbAAAAgbIAAhBQAAgcAbAAIAyAAIAAgRIhHAAQgIAAgEgEQgEgDAAgIQAAgIAEgEQAEgEAIAAIBHAAIAAgHQAAgHAEgEQAEgFAIAAQAIAAAFAFQAEAEAAAHIAAAHIBMAAQAIAAAEAEQADADAAAJQAAAGgDAEQgEAFgIAAIhMAAIAAARIAyAAQANAAAHAHQAHAHAAAOIAABBQAAANgHAHQgHAHgNAAIgyAAIAAAQIBRAAQAIAAAEAEQADADAAAIQAAAIgCADQgEAGgJAAIhRAAIAAAQQAAAGgDAFQgEAGgKAAQgIAAgFgGgARBADIAnAAQAFAAAAgEIAAgMIgsAAgAP0gBQAAAEAFAAIAnAAIAAgQIgsAAgARBgqIAsAAIAAgJQAAgGgFAAIgnAAgAP0gzIAAAJIAsAAIAAgPIgnAAQgFAAAAAGgAxnBXQgMAAgGgGQgGgGAAgMIAAhgQAAgNAGgGQAGgGAMAAIB0AAQAMAAAHAGQAGAGAAANIAABgQAAAMgGAGQgHAGgMAAgAxbgQIAAA9QAAAJAJAAIBLAAQAIAAAAgJIAAg9QAAgIgIAAIhLAAQgJAAAAAIgAOdgaIgIgFQgQgOgUgNIgDgDQgGgEAAgHQAAgHAGgFQAFgFAHAAQAFAAAFACQAaAQATAPQAFAJAAAEQAAAGgEAFQgEAGgIACQgGAAgDgCgArsgcQgJAAgFgEQgEgEAAgKQAAgJAEgFQAFgDAJAAICpAAQAKAAAEADQAEAEAAAKQAAAIgDAEQgFAGgKAAgAsogqQgEgEAAgLIAAgsQAAgOAGgHQAHgHAOAAIBlAAIAAgLQAAgIAGgHQAEgEAMAAQALAAAEAEQAHAFAAAKIAAALIBiAAQAbAAAAAcIAAAqQAAAKgEAEQgGAEgKAAQgMAAgFgFQgEgEAAgJIAAggQAAgEgFAAIjNAAQgFAAAAAEIAAAiQAAALgFAEQgFAEgLAAQgLAAgFgEgAFUgxQgFgHAAgHQABgHAGgEQApgnAgglQAMgMALAAQALAAAKALQAqAsAlAeQAFAEAAAHQAAAKgHAHQgFAFgKAAQgEAAgGgFIgRgRIAAADQAAAGgDADQgEAGgIAAIhSAAQgIAAgEgEQgDgDAAgHIgOAOQgGAGgGAAQgKAAgGgHgAHihOIgngrQgDgDgCAAIgEACIglAsIBVAAgAOrheIgJgFQgQgNgTgMIgDgDQgGgEAAgGQAAgHAGgGQAFgFAGAAQAGAAAEACQAbAPASAOQAGAIAAAEQAAAGgEAGQgEAFgJADgAjWhtIgXggIgCgDIACgGQACgEAFgCIAIgCQAGABAFAFQAGADAKAOQAGAIAAAGQAAAGgEADQgEAFgJAAQgFAAgDgCg");
	this.shape.setTransform(156.2,19.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.9,3.4,304.8,32.7);


(lib.t1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AXKCtQglgGgygXQgPgHgJgHIgDgMQAAgFADgEIg6AAQAGAGAAAIQAAAGgGAGIgcALQgnAPghAHQgKADgLABQgJAAgHgHQgEgFAAgIQAAgIAJgFQA6gPAhgNIAFgCIgqAAQgMAAgGgGQgGgGAAgMIAAiZQAAgYAYAAIBPAAIAIggIiFAAQgKAAgEgEQgFgDABgKQgBgJAFgFQAEgEAKAAIE3AAQAKAAAFAEQADADAAALQAAAIgDAEQgFAFgKAAIiHAAIgIAgIBjAAQAMAAAFAGQAHAGAAAMIAACZQAAAMgHAGQgFAGgMAAIgzAAQApASAzAMIAPAEQAGAEAAAKQAAAHgHAGQgEAFgLAAgATkBDQAAAIAIAAICqAAQAIAAAAgIIAAgQIi6AAgATkAUIC6AAIAAgWIi6AAgATkgyIAAARIC6AAIAAgRQAAgIgIAAIiqAAQgIAAAAAIgAatCmQgEgFAAgHIAAhQIhfAAQghAAABghIAAhyQgBgQAJgJQAIgIAQAAIBfAAIAAgvQAAgJAGgFQAEgGAJAAQAKAAAGAGQAFAFAAAJIAAAvIBeAAQAQAAAIAIQAIAJAAAQIAAByQAAAQgIAJQgIAIgQAAIheAAIAABQQAAAHgEAFQgFAHgMAAQgJAAgGgHgAbRAjIBJAAQAMAAAAgMIAAhOQAAgMgMAAIhJAAgAZSg3IAABOQAAAMANAAIBKAAIAAhmIhKAAQgNAAAAAMgA5SCsIgVgDQgIgFgCgNQAAgTAPgCIAFABQAPAEAJAAQAGgBABgFIAAhCIh4AAQgHAAgFgEQgEgEAAgKQAAgIAEgFQAFgDAHAAIB4AAIAAgmQgBgOATgBQAIAAAFAEQAFADAAAIIAAAmIAcAAQAIAAAEADQAEAEAAAJQgBAIgDAFQgEAFgIAAIgcAAIAABQQAAANgHAIQgIAHgQACIgZgBgAk7CsQgLgBgHgHQgEgEAAgIQAAgKAEgEQAEgFAKgCIASAAQAHAAAAgEIAAg9QgQAEgMAAQgWAAAAgUQAAgQANgDIAlgLIAAhOIghAAQgIAAgGgFQgFgEAAgMQAAgMAFgEQAFgDAJAAIAhAAIAAg6QAAgIAFgEQAFgEAKgBQATAAABARIAAA6IAVAAQAKAAAEAEQAFADAAAMQAAALgDADQgFAHgLAAIgVAAIAABAIAMgFQAGgCAEgBQALAAAEAEQAHAHAAAJQgBAIgIAGQgNAKgWAJIAABYQAAAQgIAHQgJAIgOACgAtnCoQgIgDAAgLQAAgFAFgGQAQgUAKgTQALgWADgQIgMAAQgLAAgGgGQgFgFAAgLIAAg3QAAgWAWAAIAzAAQAWAAAAAWIAAA3QAAALgGAFQgFAGgLAAIgGAAIAAADQABAIgFAOIgCAHQAJAOAdAcQAGADAAAJQAAAHgDAFQgFAGgIAAQgPAAgbgpQgKAYgKALQgHAIgLAAQgHgBgFgDgAtCACIAAAbQgBAGAHAAIAPAAQAFAAABgGIAAgbQgBgEgFAAIgPAAQgHAAABAEgA7tClQgDgEAAgHIAAh5IggAAIAAAZQAAASgDASQgHArgRAVQgGAHgMAAQgIAAgFgEQgEgFAAgIIAEgIQALgSAFgSQAGgSAAgTIAAgiIgJAAQgIAAgEgDQgEgEABgJQgBgJAFgEQAEgDAHAAIBNAAIAAgoIg1AAQgYAAAAgXIAAhRQAAgIAFgFQAFgEAIAAQAKAAAEAEQAFAFABAIIAAA9QgBAHAIAAIAgAAIAAhOQAAgIAEgFQAFgFAIAAQAIAAAGAFQAFAFAAAIIAAA+QA7gpAdgkQAGgFAFAAQAJAAAGAEQAGAFAAAHQAAAEgDAGIgIAMIBLAAQAdABAAAVQAAASgNATQgMATgYATQgRAOgaAPQgZANgjAPQgOAGgOABQgIAAgFgGQgEgEABgFQAAgHAEgEIAkgPIgegVIgDgDQgDgDAAgGQAAgFAGgFQAGgEAGAAIAIACQAhAVAJAJIAQgKIgdgVIgDgBQgDgDAAgHQAAgEAGgGQAGgEAGAAIAGACQAeATAGAHIACABIAAAAQARgNAKgKQAIgLABgIQAAgEgGAAIhWAAQgXATgdAUQgHAEgIAAQgFAAgEgCIAADYQAAAHgDAEQgFAHgLAAQgIAAgGgHgAQ3CpQgJgBgEgGQgFgGAAgIIABgIQACgFAGgDIAOgCIALAAQABAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBIAAj1QAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAgBAAIiAAAIgBADIAAETQAAANgSAAQgIAAgEgDQgEgEAAgGIAAkhQAAgYAUAAICdAAQAMAAAGAFQAFAEAAAKIAAEdQAAAMgFAFQgHAFgNAAgANSCmQgFgEAAgIIAAh8QgSADgTAAQgJAAgFgEQgEgFgBgKQAAgGAEgFQAEgDAJAAIACAAQARgUAQgWQgRgVgXgWQgJgHAAgHQAAgIAFgEQAGgFAFAAIAHABQALgOAPgfQAFgKAHAAQAFAAAIAEQAGAEAAAHQAAAHgEAJQgIASgSAaIASAWQAQgaAMgdQAGgJAHAAQAFAAAGADQAGAFAAAHQAAANgKAUQgSAkgnAxQAUgEASgFIgDgQIgBgFQgBgNANgBQANAAAEALQAEANADAPIADAeQAAANgRABQgLgBgBgLIgBgHIgOAFIAACFQAAAIgFAEQgEAEgJAAQgIAAgEgEgAocCqQgqAAgcgGQgcgFgOgLQgFgDgDAAIgEABQgLAKgNAJQgIAFgDAAQgHAAgDgCQgIgGgFgKIgBgHQABgJAIgEQAOgHAPgMQADgDABgEIAAhLQAAgBAAgBQAAAAgBgBQAAAAgBAAQAAAAgBAAIgaAAQgKgBgDgFQgEgEgBgKQAAgIAFgDQAFgFAIAAIApAAQAMAAAGAGQAGADABAMIAABdQACAMAPAFQAMAEAUACQATACAbAAICfgBQAHAAAFADQAFAGAAAJQAAAMgFAFQgDAEgMABgAvQCnQgIgDAAgKQAAgFADgGQAOgTAIgSQAJgWADgPIAAgDIgGAAQgVAAAAgVIAAg5QAAgKAGgFQAEgGALAAIAwAAQAKAAAFAGQAGAFgBAKIAAA5QAAAVgUAAIgJAAIABAGIgCANIADACQAJAHAMASQANASABAJQAAAHgGAEQgEAFgKAAQgHAAgFgGIgSgdIgLAbQgFALgFAGQgHAGgKAAQgGAAgFgDgAurABIAAAeQAAAEAEAAIAMAAQAFAAgBgEIAAgeQABgDgFAAIgMAAQgEAAAAADgA3ECjQgEgFgBgJQAAgHAFgGQA1gcAPgYQAHgJAFgPQAFgOACgUIgdAAQggAAgBgeIAAhjQAAgQAIgIQAJgIAQAAIBHAAIAIgbQAFgLAQgBQAJAAAHADQAFAEABAIIgGAYIBkAAQAQAAAIAIQAIAIAAAQIAABjQAAAOgIAIQgIAIgQAAIgOAAQAFAEAAAGIgDAJQgGATgNATIAsgFIgJgPQgEgHAAgFQAAgHAGgDQAFgDAFAAIAJACQAGAFALANQAUAfAAAOQAAAIgFAEIgCACIABAJQAAARgGAKQgHALgWABIh0AAQgagCAAgoIAAhhIgdAAQgBATgDARQgFAQgFANQgVAqgxAdQgNAIgKAAQgJAAgIgHgA0GB0IAAAEQABAKAKAAIBOAAQALAAACgDQACgBAAgFQABgFAFgEIADgBIgDgHQhLALgjABgA0GBXIANgBIAcg3IADgFIgsAAgA0NgGIBMAAQAHAAABgHIAAgYIhUAAgA2CgNQAAAHAHAAIBGAAIAAgfIhNAAgA0NhGIBUAAIAAgYQgBgHgHAAIhMAAgA2CheIAAAYIBNAAIAAgfIhGAAQgHAAAAAHgADfCpQgKgBgIgCQgIgDgFgFQgJgJABgUIAAhoIgPAEQgJAAgDgFIgCgJIgEAFQgNANgTAMIAABeQAAAOgIAHQgHAHgOACIgXAAQgKgBgGgHQgEgEAAgIQAAgJAEgFQAEgFAKgBIALAAQAFgBAAgEIAAg8QgQAGgKAAQgVAAgBgTQAAgOAOgEIAigOIAAhXIgfAAQgIAAgFgFQgFgEAAgLQAAgKAFgEQAEgEAJAAIAfAAIAAgyQAAgIAEgEQAFgEAIgBQAKAAAFAEQAFAFABAIIAAAyIAaAAQAJAAAEAEQAFADAAALQAAAKgDADQgFAHgKAAIgaAAIAABEIAIgGQAFgGAEAAQAKAAAFAFIAFAHQACgCAGgBIAUgGIAAgjIgHABQgGgBgHgFQgFgFAAgHIAEgLQAYgrAPgvQADgLAMAAQAIAAAGAEQAGAFAAAJQgBALgFANIB9AAQAKAAADAEQAEADABALQAAAJgDAEQgFAGgKAAIiLAAIgTAkIAEAAQAJAAADADQAGAFAAAIIAAAWIAjgMIAAgjQgBgIAGgFQAEgFAJAAQAIAAAEAFQAFAFAAAIIAAAYQAtgOAEAAQAOAAAIAGQAIAFAAARQAAAzgEAmQgHAOgTAAIgOAAIgPgCQgGgCgDgFQgBgDAAgIQAAgHADgEQADgDAFAAIAMAAQAJAAAAgHIAAgxQAAgFgHAAIgjAMIAABbQAAAIgDAEQgEAGgKAAQgJAAgGgGQgDgFAAgHIAAhRIgjAMIAABrQAAAHADADQAEAEAHABIBbAAQAKgCACgGQAEgGgBgIIABgTQACgNAQAAQAJAAAFAEQAFADACALQAAAUgDANQgCAOgEAHQgFAIgKADQgJAEgPABgAwUCnQgHgCgEgGQgCgGAAgIQABgHAFgEQAEgEAHAAIACAAIAIABQAHAAAAgHIAAg+IgiAAQgDAzgHAmIgGAKQgDAGgLAAQgIAAgFgEQgEgEAAgHIACgRQAHggAEg8IABirQAAgOAHgHQAIgHAOAAIAuAAQAOAAAHAHQAHAIAAAPIAAEBQAAAMgCAIQgCAHgEAEQgGAHgWAAgAwgAaIAhAAIAAg0IghAAgAwghxIAAA0IAhAAIAAguQAAgOgIAAIgRAAQgHAAgBAIgAGuCeQgKAAgEgEQgGgFAAgKQAAgKAGgFQAEgEAKAAICFAAIAAgtIh0AAQgIAAgEgFQgFgEAAgKQAAgJAFgFQAEgEAIAAIB0AAIAAgYQAAgHAHgGQAEgDAKAAQALAAAEADQAGAEAAAJIAAAYIB0AAQAJAAAFAEQAEADAAALQAAAIgEAFQgEAGgKAAIh0AAIAAAtICGAAQAKAAAFAEQAEADAAAMQAAAJgEAEQgEAGgLAAgAiuCdQgdAAAAgeIAAjPQAAgeAdAAIAVAAQAHgVADgYQAFgQAPAAQAIAAAIAFQAHAFAAALIAAAFIgKAjIBAAAQAeAAAAAeIAADPQAAAegeAAgAijBtQAAAJAIAAIBaAAQAIAAAAgJIAAhFIhqAAgAijg+IAAA+IBqAAIAAg+QAAgKgIAAIhaAAQgIAAAAAKgAMaCRQgFgEAAgGIADgQQAFgVAHgqQADgMAKAAQAHAAAFACQAFADAAAIIgBALQgHAugFAaQgDAIgKABQgJAAgFgEgA6WCKQgMgWgQgUQgDgDgBgDQABgJAGgEQAHgDAGAAQAHAAAGAEQAIAHALAQQAMAQABAJQAAAHgGAFQgFAFgLAAQgHAAgEgFgAN/B4QgBglgEgXIAAgGQAAgLAMAAQANAAADAIQAFAeABAlQAAANgRAAQgLAAgBgLgAoIB4QgEgGAAgGIAAgSIhdAAQgJAAgEgEQgDgEAAgKQAAgIADgEQAEgEAJAAIBdAAIAAgSIg2AAQgdAAAAgeIAAhGQAAgeAdAAIA2AAIAAgTIhNAAQgJAAgEgEQgDgEAAgJQAAgIADgFQAEgDAJAAIBNAAIAAgIQAAgIAFgEQAEgGAJAAQAJAAAFAGQAFAEAAAIIAAAIIBRAAQAKAAAEADQADAEAAAJQAAAHgCAEQgFAGgKAAIhRAAIAAATIA1AAQAPAAAIAHQAHAIAAAPIAABGQAAAPgHAHQgIAIgPAAIg1AAIAAASIBYAAQAJAAAEAEQADADAAAJQAAAIgDAEQgEAGgJAAIhYAAIAAASQAAAGgDAFQgFAHgLAAQgJAAgFgGgAnnAFIAqAAQAGAAgBgFIAAgMIgvAAgAo7AAQAAAFAFAAIAqAAIAAgRIgvAAgAnngrIAvAAIAAgKQABgHgGAAIgqAAgAo7g1IAAAKIAvAAIAAgRIgqAAQgFAAAAAHgAPzBhQgLAAgFgFQgGgFAAgKIAAgqIgBAAQgHAAgEgEQgDgDAAgIQAAgIADgDQAEgEAHAAIAcAAIAAgVIgcAAQgHAAgEgEQgDgEAAgJQAAgJADgDQADgDAIAAIAKAAIgQgkIgBgFIABgFQACgEAEgCIAHgBQAGABAFADQAFAHALAXQADALACAIIAMAAIAAgCQAIgVAHgXQACgJAGAAQAKAAADADQAHADAAAJIgDAKIgKAeIAHAAQAHAAADADQAFADAAAJQAAAIgDADQgEAGgIAAIgcAAIAAAVIAcAAQAIAAADAEQAEACAAAJQAAAHgDADQgEAFgIAAIg3AAIAAAbQAAAFAGAAIAtAAQAFAAADAEQADAEAAAHQAAAIgDADQgDAEgFAAgALGgJIgSgWQgqAJgwAFQhMAJhTAAQgLAAgEgEQgGgEAAgLQABgIADgFQAEgGANAAIAhAAIAkhEIhNAAQgKAAgGgFQgEgEAAgLQAAgKAEgEQAGgFAKAAIEtAAQALAAAEAFQAEADAAALQAAAJgDAEQgFAHgLAAIi0AAIgjBCQA0gCBagKIgagWQgDgHAAgGQgBgGAIgFQAFgEAIAAQAHAAAJAGQASAMARAQQARAQAQAVQAHAJABAJQAAALgFAGQgGAEgKAAQgKgBgFgIgAqagaIgJgGQgRgOgVgPIgEgDQgFgFgBgHQAAgIAGgFQAGgGAHAAQAGAAAFADQAcARAVARQAGAJAAAEQAAAGgFAGQgEAHgJACQgGAAgEgCgAvVg0QgFgHABgIQAAgHAHgFQAsgpAjgpQAMgNANAAQAMAAAMAMQAsAwAoAgQAGAFAAAHQAAALgIAHQgFAGgLAAQgEAAgHgGIgSgRIAAACQAAAIgDADQgFAGgJAAIhZAAQgIAAgEgFQgDgDgBgHIgPAPQgGAHgIAAQgLAAgGgJgAs7hTIgqguQgCgDgDAAIgEACIgpAvIBcAAgAqLhkIgJgFQgRgOgVgNIgEgDQgGgGAAgGQAAgIAGgGQAGgGAHAAQAGAAAFADQAdAQATAQQAHAIAAAFQgBAGgEAGQgEAGgKADg");
	this.shape.setTransform(187.2,17.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,374.3,35.1);


(lib.pic = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0.4)","rgba(255,255,255,0)"],[0,1],-47.8,25.6,2.4,-24.5).s().p("ApmBLIAAmtITNAAIAALFg");
	this.shape.setTransform(65.5,43.5,0.935,1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(5,0,0,3).p("Ao5I6IAAxzIRzAAIAARzg");
	this.shape_1.setTransform(66,66);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B4B4B4").s().p("Ao5I6IAAxzIRzAAIAARzg");
	this.shape_2.setTransform(66,66);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(8,8,115,115);


(lib.like = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnLHJQgPAAgLgKQgLgLgBgQIgnmuQAAgRAMgLQALgLAQAAIE2AAQASAAANAPIAbgSIB/jOQAChRAAgwQAAgUAQgSQARgTAagHQAcgJAYAIQAZAHAQAWQAwBHALA2QAMBEgaB0IAsAAQC6gBAmABQAZABATAVQAUAVAFAgQAGAegKAYQgJAZgVARQAMAdgHAgQgJAigZAUQAHAWgEAXQgHAlgbAbQANAggQAmQgOAigeAUQgdATgkAAImOAAIhOgaIAAAVQAAAQgLALQgMALgQAAgAm+GWID2AAIAAmVIkbAAgABQmTQgLACgJAGQgHAFgBAEQAAAggFBqIAAAGIiLDkIg4AiIAAFDIBWAeIGGAAQAWAAASgNQAOgMAHgRQAMgagOgNIgYgZIAfgQQALgFAIgMQAHgMADgOQADgTgIgJIgegeIAogNQAVgHAFgXQADgMgDgMQgDgLgFgEIgcgcIAkgPQAWgJAGgSQAEgNgDgPQgCgOgHgKQgGgIgFAAQgkgBi6ABIhtAAIAHggQAfh8gKhBQgHgugshBQgHgKgOAAIgIABg");
	this.shape.setTransform(53.7,45.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,107.4,91.5);


(lib.fb = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AB1F4IAAkkIByAAIAYhsIiKAAIAAghQAAgyARgSQASgSArAAQAhAAAcAFIAChqQgwgKg5AAQgcAAgbAMQgSAIgXAPQgfAVgRAtQgJAbAAA9IAAApIhqAAIAABsIBqAAIAAEkIkcAAQgmAAgagbQgbgaAAgmIAAo5QAAgmAbgaQAagbAmAAII5AAQAmAAAaAbQAbAaAAAmIAAI5QAAAmgbAaQgaAbgmAAg");
	this.shape.setTransform(37.6,37.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,75.3,75.3);


(lib.bowser = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(3).p("AipstIAhhxQAAgJAGgGQAFgFAJAAIF/AAQAIAAAGAFQAGAGAAAJIAnCJIHxAAIgniJQAAgJgGgGQgGgFgIAAImBAAQgJAAgFAFQgGAGAAAJIghBxAM3sVIHxAAIgoiJQAAgJgGgGQgFgFgJAAImBAAQgIAAgGAFQgGAGAAAJIggBxAVtsVIgCAAIAAcdMgrVAAAMAAAggPMArVAAAIAADyIhDAAAUYo4MgiCAAAIAAiMMAiCAAAgAFGsVInvAAInqAAIgGgYIghhxQAAgJgGgGQgFgFgJAAImBAAQgIAAgGAFQgGAGAAAJIgnCJIjdAAAipsVIgniJQAAgJgGgGQgFgFgJAAImBAAQgIAAgGAFQgGAGAAAJIggBxA0SnpMAoqAAAIAAWoMgoqAAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAmg9IBsA9IhsA+gAiRAAIBsg9IAAB7g");
	this.shape_1.setTransform(-111.5,-63.9);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-138.8,-103.2,277.7,206.6);


(lib.arrow = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgrAdIh8AAIAAg5IB8AAIgshLID/BnIj/Bog");
	this.shape.setTransform(16.9,10.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,33.7,21);


(lib.p3 = function() {
	this.initialize();

	// Layer 1
	this.text = new cjs.Text("3", "66px Arial", "#FFFFFF");
	this.text.textAlign = "center";
	this.text.lineHeight = 68;
	this.text.lineWidth = 65;
	this.text.setTransform(64.4,26.5);

	this.instance = new lib.pic();
	this.instance.setTransform(62.8,62.8,1,1,0,0,0,62.8,62.8);

	this.addChild(this.instance,this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(8,8,115,115);


(lib.p2 = function() {
	this.initialize();

	// Layer 1
	this.text = new cjs.Text("2", "66px Arial", "#FFFFFF");
	this.text.textAlign = "center";
	this.text.lineHeight = 68;
	this.text.lineWidth = 65;
	this.text.setTransform(64.4,26.5);

	this.instance = new lib.pic();
	this.instance.setTransform(62.8,62.8,1,1,0,0,0,62.8,62.8);

	this.addChild(this.instance,this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(8,8,115,115);


(lib.p1 = function() {
	this.initialize();

	// Layer 1
	this.text = new cjs.Text("1", "66px Arial", "#FFFFFF");
	this.text.textAlign = "center";
	this.text.lineHeight = 68;
	this.text.lineWidth = 65;
	this.text.setTransform(64.4,26.5);

	this.instance = new lib.pic();
	this.instance.setTransform(62.8,62.8,1,1,0,0,0,62.8,62.8);

	this.addChild(this.instance,this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(8,8,115,115);


(lib.GIF = function() {
	this.initialize();

	// Layer 1
	this.text = new cjs.Text("GIF", "56px Arial", "#FFFFFF");
	this.text.textAlign = "center";
	this.text.lineHeight = 58;
	this.text.lineWidth = 109;
	this.text.setTransform(64,31.5);

	this.instance = new lib.pic();
	this.instance.setTransform(63.3,62.8,1,1,0,0,0,62.8,62.8);

	this.addChild(this.instance,this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(8.5,8,115,115);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;